###
POST http://localhost:3003/api/blogs 
content-type: application/json

{
    "title": "10 simple ways to lose weight",
    "author": "Niko Matsakis",
    "url": "https://smallcultfollowing.com/babysteps/blog/2023/10/20/losingweight223/",
    "likes": "1"
}
###
DELETE 