# fly.toml app configuration file generated for backend214903249 on 2023-11-26T23:39:33+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend214903249"
primary_region = "syd"

[build]

[env]
PORT = "3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
