###
GET  http://localhost:3002/api/persons
###
GET http://localhost:3002/api/persons/656442fe825ec201e9501232

###
DELETE http://localhost:3002/api/persons/4

###
POST http://localhost:3002/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "GHOSTBOY",
    "number": "123-334"
}

###
PUT http://localhost:3002/api/persons/656442fe825ec201e9501232 HTTP/1.1
content-type: application/json

{
    "name": "GHOSTBOY",
    "number": "123-335"
}
###
POST http://localhost:3002/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "GH",
    "number": "123-334"
}